### ISSUE TITLE
Publish fmriprep datasets for neuroscout-datasets using datalad

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#396]
Need to update fmriprep inputs to neuroscout now that RC1-compliant fmriprep has been released.

- One option is to run fmriprep on OpenNeuro (not functional right now)
- We could also preprocess and push to `neuroscout-datasets` in the meantime (and probably want to support this for datasets not on OpenNeuro anyway)

**Comment by adelavega** [comment]
In progress. We had a data allocaton on corral, and I'm going to try to make some datalad datasets that are hosted on there.

**Comment by adelavega** [comment]
`SherlockMerlin` is done. Now need to do `life`

**Comment by adelavega** [comment]
For future reference, here's the steps that are necessary.

First, I created a folder on corral using lonestar, with global read permissions called `neuroscout-datasets`. This folder is mapped to :`http://web.corral.tacc.utexas.edu/neuroscout-datasets/`

```
ssh delavega@ls5.tacc.utexas.edu
cd /corral-repl/utexas/neuroscout/
chmod a+rx -R neuroscout-datasets/
```
The following commands all new folders created within it will also have global read permissions:
`setfacl -d -m o::rx neuroscout-datasets`

Then, on drakh, I navigate to the datasets folder

```
datalad create life
```
and run fmriprep
```
docker run -d -v /media/alejandro/neuroscout-data/neuroscout/datasets:/data poldracklab/fmriprep /data/raw/life /data/neuroscout-datasets/life_local participant --participant-label sub-rid000019 --fs-license-file /data/other/license.txt --fs-no-reconall --nthreads=18
```
Then I set up this folder to be published
```
cd life
datalad add .

datalad create-sibling -s mddatasrc delavega@ls5.tacc.utexas.edu:/corral-repl/utexas/neuroscout/neuroscout-datasets/life --as-common-datasrc tacc-corral --target-url https://web.corral.tacc.utexas.edu/neuroscout-datasets/life/.git --ui true

datalad create-sibling-github --github-organization neuroscout-datasets --github-login adelavega --github-passwd PSSWD --publish-depends mddatasrc --access-protocol ssh life
datalad publish --to github --transfer-data all
```

This should push to github and corral, and be available at the target URL.

Sometimes it is necessary to run:
`datalad update -s mdatasrc` to fetch sibling changes
or `git annex fsck` if verification fails.

**Comment by rschmaelzle** [comment]
Hello,
i am not sure this is the correct way to submit an issue here. Happy to learn how....

I tried to run an analysis, but ran into issues downloading sub19 from studyforrest from tacc (see full report below). I figured that this might perhaps be most closely related to this issue (perhaps wrong).
Great project - I hope that once i get better understanding of the code underlying neuroscout, I can be of more help. Best ralf.

----error message - see very bottom form abort
```

INFO:root:Running analysis : 9ExrM
INFO:root:Downloading bundle...
INFO:root:Bundle installed at /work/studyforrest/neuroscout-bundles/9ExrM
[INFO   ] Cloning https://github.com/neuroscout-datasets/studyforrest/ to '/work/studyforrest/preproc' 
INFO   :datalad.distribution.clone:Cloning https://github.com/neuroscout-datasets/studyforrest/ to '/work/studyforrest/preproc'
Total (207 ok, 1 failed out of 208):  99%|▉| 14.5G/14.6G [35:18<00:45, 2.94MB/s][WARNING] Running get resulted in stderr output: download failed: HandshakeFailed (Error_Packet "partial packet: expecting 4666 bytes, got: 1369")              
download failed: Not Found:  60%|██████▋    | 63.6M/106M [00:20<00:16, 2.57MB/s]
git-annex: get: 1 failedgz:   8%|▉           | 10.7M/132M [00:08<02:12, 917kB/s]
 
WARNING:datalad.annex:Running get resulted in stderr output: download failed: HandshakeFailed (Error_Packet "partial packet: expecting 4666 bytes, got: 1369")
download failed: Not Found
git-annex: get: 1 failed

                                                                                [ERROR  ] from tacc-corral...; Unable to access these remotes: tacc-corral; Try making some of these repositories available:; 	18cd0068-e5ee-40be-9742-b6bdf9c37399 -- [tacc-corral];  	978f3119-b959-49d8-91eb-9c2e52db0710 -- alejandro@drakh:/media/alejandro/neuroscout-data/neuroscout/datasets/neuroscout-datasets/forrest; ; (Note that these git remotes have annex-ignore set: origin) [get(/work/studyforrest/preproc/fmriprep/sub-15/ses-movie/func/sub-15_ses-movie_task-movie_run-3_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz)] 
ERROR  :datalad.distribution.get:from tacc-corral...; Unable to access these remotes: tacc-corral; Try making some of these repositories available:; 	18cd0068-e5ee-40be-9742-b6bdf9c37399 -- [tacc-corral];  	978f3119-b959-49d8-91eb-9c2e52db0710 -- alejandro@drakh:/media/alejandro/neuroscout-data/neuroscout/datasets/neuroscout-datasets/forrest; ; (Note that these git remotes have annex-ignore set: origin) [get(/work/studyforrest/preproc/fmriprep/sub-15/ses-movie/func/sub-15_ses-movie_task-movie_run-3_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz)]
Traceback (most recent call last):
  File "/src/neuroscout/neuroscout_cli/commands/install.py", line 70, in download_data
    get(paths)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/wrapt/wrappers.py", line 564, in __call__
    args, kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/datalad/interface/utils.py", line 478, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/wrapt/wrappers.py", line 564, in __call__
    args, kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/datalad/interface/utils.py", line 466, in return_func
    results = list(results)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/datalad/interface/utils.py", line 454, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'type': 'file', 'status': 'error', 'path': '/work/studyforrest/preproc/fmriprep/sub-15/ses-movie/func/sub-15_ses-movie_task-movie_run-3_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz', 'action': 'get', 'annexkey': 'MD5E-s132422824--f4e935c7605b1a7d1c2968d6954c6ef4.nii.gz', 'message': 'from tacc-corral...; Unable to access these remotes: tacc-corral; Try making some of these repositories available:; \t18cd0068-e5ee-40be-9742-b6bdf9c37399 -- [tacc-corral];  \t978f3119-b959-49d8-91eb-9c2e52db0710 -- alejandro@drakh:/media/alejandro/neuroscout-data/neuroscout/datasets/neuroscout-datasets/forrest; ; (Note that these git remotes have annex-ignore set: origin)'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/bin/neuroscout", line 11, in <module>
    load_entry_point('neuroscout-cli', 'console_scripts', 'neuroscout')()
  File "/src/neuroscout/neuroscout_cli/cli.py", line 60, in main
    command(deepcopy(args)).run()
  File "/src/neuroscout/neuroscout_cli/commands/run.py", line 22, in run
    bundle_path = install.run()
  File "/src/neuroscout/neuroscout_cli/commands/install.py", line 85, in run
    return self.download_data()
  File "/src/neuroscout/neuroscout_cli/commands/install.py", line 77, in download_data
    raise ValueError("Datalad failed. Reason: {}".format(message))
ValueError: Datalad failed. Reason: from tacc-corral...; Unable to access these remotes: tacc-corral; Try making some of these repositories available:; 	18cd0068-e5ee-40be-9742-b6bdf9c37399 -- [tacc-corral];  	978f3119-b959-49d8-91eb-9c2e52db0710 -- alejandro@drakh:/media/alejandro/neuroscout-data/neuroscout/datasets/neuroscout-datasets/forrest; ; (Note that these git remotes have annex-ignore set: origin)
(base) cas3401schmaelzle:~ Ralf$ docker run --rm -it -v /Users/Ralf/Desktop/neuroscout:/out neuroscout/neuroscout-cli run /out 9ExrM
INFO:root:Running analysis : 9ExrM
INFO:root:Downloading bundle...
INFO:root:Bundle installed at /work/studyforrest/neuroscout-bundles/9ExrM
[INFO   ] Cloning https://github.com/neuroscout-datasets/studyforrest/ to '/work/studyforrest/preproc' 
INFO   :datalad.distribution.clone:Cloning https://github.com/neuroscout-datasets/studyforrest/ to '/work/studyforrest/preproc'
Total (207 ok, 1 failed out of 208):  99%|▉| 14.5G/14.6G [40:51<01:17, 1.82MB/s][WARNING] Running get resulted in stderr output: download failed: HandshakeFailed Error_EOF                                                                     
download failed: Not Found                                                      
git-annex: get: 1 failedgz:  16%|█▉          | 23.2M/146M [00:34<03:03, 668kB/s] 
WARNING:datalad.annex:Running get resulted in stderr output: download failed: HandshakeFailed Error_EOF
download failed: Not Found
git-annex: get: 1 failed

                                                                                [ERROR  ] from tacc-corral...; Unable to access these remotes: tacc-corral; Try making some of these repositories available:; 	18cd0068-e5ee-40be-9742-b6bdf9c37399 -- [tacc-corral];  	978f3119-b959-49d8-91eb-9c2e52db0710 -- alejandro@drakh:/media/alejandro/neuroscout-data/neuroscout/datasets/neuroscout-datasets/forrest; ; (Note that these git remotes have annex-ignore set: origin) [get(/work/studyforrest/preproc/fmriprep/sub-19/ses-movie/func/sub-19_ses-movie_task-movie_run-6_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz)] 
ERROR  :datalad.distribution.get:from tacc-corral...; Unable to access these remotes: tacc-corral; Try making some of these repositories available:; 	18cd0068-e5ee-40be-9742-b6bdf9c37399 -- [tacc-corral];  	978f3119-b959-49d8-91eb-9c2e52db0710 -- alejandro@drakh:/media/alejandro/neuroscout-data/neuroscout/datasets/neuroscout-datasets/forrest; ; (Note that these git remotes have annex-ignore set: origin) [get(/work/studyforrest/preproc/fmriprep/sub-19/ses-movie/func/sub-19_ses-movie_task-movie_run-6_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz)]
Traceback (most recent call last):
  File "/src/neuroscout/neuroscout_cli/commands/install.py", line 70, in download_data
    get(paths)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/wrapt/wrappers.py", line 564, in __call__
    args, kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/datalad/interface/utils.py", line 478, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/wrapt/wrappers.py", line 564, in __call__
    args, kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/datalad/interface/utils.py", line 466, in return_func
    results = list(results)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/datalad/interface/utils.py", line 454, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'type': 'file', 'status': 'error', 'path': '/work/studyforrest/preproc/fmriprep/sub-19/ses-movie/func/sub-19_ses-movie_task-movie_run-6_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz', 'action': 'get', 'annexkey': 'MD5E-s140526956--1359d6a43ba6cee74d4fc0315bf2527a.nii.gz', 'message': 'from tacc-corral...; Unable to access these remotes: tacc-corral; Try making some of these repositories available:; \t18cd0068-e5ee-40be-9742-b6bdf9c37399 -- [tacc-corral];  \t978f3119-b959-49d8-91eb-9c2e52db0710 -- alejandro@drakh:/media/alejandro/neuroscout-data/neuroscout/datasets/neuroscout-datasets/forrest; ; (Note that these git remotes have annex-ignore set: origin)'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/bin/neuroscout", line 11, in <module>
    load_entry_point('neuroscout-cli', 'console_scripts', 'neuroscout')()
  File "/src/neuroscout/neuroscout_cli/cli.py", line 60, in main
    command(deepcopy(args)).run()
  File "/src/neuroscout/neuroscout_cli/commands/run.py", line 22, in run
    bundle_path = install.run()
  File "/src/neuroscout/neuroscout_cli/commands/install.py", line 85, in run
    return self.download_data()
  File "/src/neuroscout/neuroscout_cli/commands/install.py", line 77, in download_data
    raise ValueError("Datalad failed. Reason: {}".format(message))
ValueError: Datalad failed. Reason: from tacc-corral...; Unable to access these remotes: tacc-corral; Try making some of these repositories available:; 	18cd0068-e5ee-40be-9742-b6bdf9c37399 -- [tacc-corral];  	978f3119-b959-49d8-91eb-9c2e52db0710 -- alejandro@drakh:/media/alejandro/neuroscout-data/neuroscout/datasets/neuroscout-datasets/forrest; ; (Note that these git remotes have annex-ignore set: origin)

```

**Comment by adelavega** [comment]
Hi @rschmaelzle. Sorry, I just saw this. I realize you have successfully run a few analyses. Were you you able to fix this problem?

Next time, can you file a new issue or feel free to email me? I didn't catch this until now.

**Comment by rschmaelzle** [comment]
HI @adelavega, thank you for the reply. I cannot remember how i fixed, but somehow it worked out. It may have been TACC, or my docker, or some interaction. Thank you very much and all the best with the cool project. ralf (closing now)
