### ISSUE TITLE
Starting up local dev server

### ISSUE THREAD

**Issue by Shotgunosine** [neuroscout/neuroscout#457]
I'm having some trouble following the instructions in the readme to start a local dev server. @adelavega has helped me debug some of them, namely renaming neuroscout/config/example_app.py to app.py.

After that the monitor container seems to be dying because it can't find tasks:
```
monitor_1     | flower   -> flower:0.9.2 tornado:5.1.1 babel:2.6.0
monitor_1     | software -> celery:4.2.1 (windowlicker) kombu:4.2.2-post1 py:3.6.6
monitor_1     |             billiard:3.5.0.5 redis:3.0.1
monitor_1     | platform -> system:Linux arch:64bit, ELF imp:CPython
monitor_1     | loader   -> celery.loaders.app.AppLoader
monitor_1     | settings -> transport:redis results:redis://redis:6379/0
monitor_1     |
monitor_1     |
monitor_1     |
monitor_1     | Traceback (most recent call last):
monitor_1     |   File "/usr/local/bin/flower", line 11, in <module>
monitor_1     |     load_entry_point('flower==0.9.2', 'console_scripts', 'flower')()
monitor_1     |   File "/usr/local/lib/python3.6/site-packages/flower/__main__.py", line 11, in main
monitor_1     |     flower.execute_from_commandline()
monitor_1     |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
monitor_1     |     argv = self.setup_app_from_commandline(argv)
monitor_1     |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
monitor_1     |     self.app = self.find_app(app)
monitor_1     |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 501, in find_app
monitor_1     |     return find_app(app, symbol_by_name=self.symbol_by_name)
monitor_1     |   File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 359, in find_app
monitor_1     |     sym = symbol_by_name(app, imp=imp)
monitor_1     |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 504, in symbol_by_name
monitor_1     |     return imports.symbol_by_name(name, imp=imp)
monitor_1     |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
monitor_1     |     module = imp(module_name, package=package, **kwargs)
monitor_1     |   File "/usr/local/lib/python3.6/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
monitor_1     |     return imp(module, package=package)
monitor_1     |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
monitor_1     |     return _bootstrap._gcd_import(name[level:], package, level)
monitor_1     |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
monitor_1     |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
monitor_1     |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
monitor_1     | ModuleNotFoundError: No module named 'tasks'
```

I decided to ignore that and press on. I tried connecting to local host and got a 404 error, but the neuroscot and nginx containers did at least receive the request:

```
neuroscout_1  | [2019-01-17 22:52:14 +0000] [9] [DEBUG] GET /
nginx_1       | 172.19.0.1 - - [17/Jan/2019:22:52:14 +0000] "GET / HTTP/1.1" 404 209 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
neuroscout_1  | [2019-01-17 22:52:15 +0000] [8] [DEBUG] GET /favicon.ico
nginx_1       | 172.19.0.1 - - [17/Jan/2019:22:52:15 +0000] "GET /favicon.ico HTTP/1.1" 404 209 "http://localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/71.0.3578.98 Safari/537.36"
neuroscout_1  | [2019-01-17 22:52:28 +0000] [8] [DEBUG] GET /
nginx_1       | 172.19.0.1 - - [17/Jan/2019:22:52:28 +0000] "GET / HTTP/1.1" 404 209 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
neuroscout_1  | [2019-01-17 22:52:44 +0000] [8] [DEBUG] GET /
nginx_1       | 172.19.0.1 - - [17/Jan/2019:22:52:44 +0000] "GET / HTTP/1.1" 404 233 "-" "Wget/1.17.1 (linux-gnu)"
neuroscout_1  | [2019-01-17 22:53:43 +0000] [8] [DEBUG] GET /
nginx_1       | 172.19.0.1 - - [17/Jan/2019:22:53:43 +0000] "GET / HTTP/1.1" 404 233 "-" "Wget/1.17.1 (linux-gnu)"
```

Finally I tried this command `docker-compose exec neuroscout bash init_reset.sh` but init_reset.sh is not there and I can't actually find it in the repo, though I don't entirely trust githubs search function. 

Thanks for all the help so far!

**Comment by Shotgunosine** [comment]
Running `db init` returns an error:
```
nielsond@promethium:/store/data/KRNS_BIDS/analysis_files/neuroscout_experiment/neuroscout$ docker-compose exec neuroscout python manage.py db init                                                          
Traceback (most recent call last):
  File "manage.py", line 85, in <module>
    manager.run()
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/__init__.py", line 106, in init
    command.init(config, directory, 'flask')
  File "/usr/local/lib/python3.6/site-packages/alembic/command.py", line 41, in init
    raise util.CommandError("Directory %s already exists" % directory)
alembic.util.exc.CommandError: Directory /migrations/migrations already exists
```
But I can shell into the container, remove /migrations/migrations and then run `db init`.

After that I can run migrate and upgrade, and add a user.

Now when I try to start the front end after running `yarn start` I get:
```
Failed to compile.

./src/App.tsx
Module not found: Can't resolve './config' in '/neuroscout/frontend/src'
```

So I went and edited config.ts.example by taking out the google_client_id and setting the server url to localhost. After trying to bring up the front end again, it complained about not having a google_client_id. So I went and got a google_client_id and now yarn seems to start fine. I'm still having trouble connecting to localhost, but that might be because I'm setting this up on a remote server. I'm going to try doing it on my own machine and see how far I get.

**Comment by adelavega** [comment]
Cool, well done on the init. Reason is we now commit our migrations, and the db is not really designed to be started empty anymore, but what you did is correct.

Ah, you're setting this up on a remote server?

**Comment by adelavega** [comment]
I'm going to close this with #458
