### ISSUE TITLE
Report is generated prior to contrast creation

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#537]
This error has been occuring frequenly. My guess is that its due to a variable that is not available for all runs. But if this is the case, we should make a nicer warning with #534 

This occurs in `wk669` for example

```
Traceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task R = retval = fun(*args, **kwargs) File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__ return self.run(*args, **kwargs) File "/celery_worker/tasks.py", line 48, in generate_report analysis, predictor_events, bids_dir, run_ids) File "/celery_worker/compile.py", line 120, in build_analysis bids_analysis.setup(**entities) File "/usr/src/app/src/pybids/bids/analysis/analysis.py", line 89, in setup b.setup(input_nodes, drop_na=drop_na, **selectors) File "/usr/src/app/src/pybids/bids/analysis/analysis.py", line 206, in setup node_coll = self._concatenate_input_nodes(input_nodes) File "/usr/src/app/src/pybids/bids/analysis/analysis.py", line 166, in _concatenate_input_nodes return BIDSVariableCollection.from_df(data, entities, self.level) File "/usr/src/app/src/pybids/bids/variables/kollekshuns.py", line 150, in from_df return BIDSVariableCollection(variables) File "/usr/src/app/src/pybids/bids/variables/kollekshuns.py", line 38, in __init__ raise ValueError("No variables were provided") ValueError: No variables were provided 
```

**Comment by adelavega** [comment]
Okay, this problem doesn't seem to replicate that often, so my guess is that sometimes it posts and tries to get a report *before* contrasts are added in, which would make sense

**Comment by adelavega** [comment]
Yep, it looks like if you don't add contrasts, and click "Next" , even though it won't let you advance, it still triggers the report, which will fail because it needs at least one contrast. 

Changing this to a frontend bug.
