### ISSUE TITLE
docker build neuroscout fails

### ISSUE THREAD

**Issue by bpinsard** [neuroscout/neuroscout#745]
When I try to start the whole neuroscout stack using docker-compose, there is an error regarding missing tensorflow during the build of neuroscout image.

```
$docker-compose up -d

..
..
..

Step 10/31 : RUN python -m pliers.support.setup_yamnet
 ---> Running in 8614270feab6
	Downloading model repository...

Model repository downloaded at /root/pliers_data/yamnet , size: 4096 bytes

Model file downloaded.

/root/pliers_data/yamnet
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/src/pliers/pliers/support/setup_yamnet.py", line 43, in <module>
    setup_yamnet()
  File "/usr/src/app/src/pliers/pliers/support/setup_yamnet.py", line 40, in setup_yamnet
    runpy.run_path(str(test_path), run_name='__main__')
  File "/usr/local/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/local/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/pliers_data/yamnet/yamnet_test.py", line 19, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
ERROR: Service 'neuroscout' failed to build: The command '/bin/sh -c python -m pliers.support.setup_yamnet' returned a non-zero code: 1
```

**Comment by adelavega** [comment]
Thanks. That should be easily fixed by adding tensorflow as a dependency. Unfortunately, travis-ci doesn't catch these sort of issues as they are related to the docker build.

**Comment by adelavega** [comment]
Actually ill just remove `RUN python -m pliers.support.setup_yamnet` as its not strictly necessary except for the AudioSet extractor
