### ISSUE TITLE
Failed to run neuroscout due to connection error

### ISSUE THREAD

**Issue by SucyLi** [neuroscout/neuroscout#793]
Hi,

I tried to follow documentation and run neuroscout on our server. This is the command I used:

`docker run --rm -it -v <my local path>:/out neuroscout/neuroscout-cli run /out wJ3ex`

However, I got a connection error as shown in this text file: [error.txt](https://github.com/neuroscout/neuroscout/files/4874981/error.txt)

Do you have any ideas how to address this issue? Thanks!

**Comment by adelavega** [comment]
Hi thank you for the bug report!

Can you try this again? It's surprising as it suggests that the server is down, but as far as I can tell it's not. 

What environment are you running in? Docker may have issues accessing your internet connection.

**Comment by adelavega** [comment]
@SucyLi can you confirm?

**Comment by SucyLi** [comment]
Hi @adelavega I tried to run again but it still doesn't work with same error message. I am running on Linux environment of our server. I can run other Docker apps without issues. Thanks for your help.

**Comment by adelavega** [comment]
Strange. It's possible that your docker environment for some reason lacks internet connectivity. 

Looks like the URL it's failing on is: http://neuroscout.org/api/analyses/wJ3ex/bundle
which works for me now. I also tried running neuroscout-cli in docker and it also worked for me.

Two things you can try:
1) Make sure the neuroscout-cli is up to date: `docker pull neuroscout/neuroscout-cli`
and try again

2) Check that the server your own can reach the URL:
`wget http://neuroscout.org/api/analyses/wJ3ex/bundle`

That should yield an output like this:
```
--2020-07-24 11:59:39--  http://neuroscout.org/api/analyses/wJ3ex/bundle
Resolving neuroscout.org (neuroscout.org)... 128.83.207.2
Connecting to neuroscout.org (neuroscout.org)|128.83.207.2|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://neuroscout.org/api/analyses/wJ3ex/bundle [following]
--2020-07-24 11:59:40--  https://neuroscout.org/api/analyses/wJ3ex/bundle
Connecting to neuroscout.org (neuroscout.org)|128.83.207.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 82226 (80K) [application/x-tar]
Saving to: ‘bundle’

bundle              100%[===================>]  80.30K  --.-KB/s    in 0.04s   

2020-07-24 11:59:40 (2.01 MB/s) - ‘bundle’ saved [82226/82226]
```



3) Verify that the docker environment can reach the 
site:

`docker run --rm -it --entrypoint=bash  neuroscout/neuroscout-cli`

That will drop you into bash in the docker environment. Now type the following:

```
source activate neuro && python -c "from pyns import Neuroscout; print(Neuroscout().analyses.bundle('wJ3ex'))"
```

That should output with no error something lke this (but longer):

```
xfb\xf2\xdd\xe2\xafo\xbf}y\xb2\x98\n"\xef6\xeb\xabS\xdbw\xbb\xdd\xdd\xf6\xf3\x97/\xff\xb0\xda\xbd\xbb\x7f{y\xb5~\xffr`\xdf\xf6j}\xbf\xfb\xec\xe1\xe6\xdb\xd3\x9b|X\xdc\xac\xae\xc7\x04z\x03\x0er\x93\xf4\xf6\xf6\xf7\x9b\xbb\xdf\xf8W\xff7\x0cd\xc8_7K\xcd\xcf\xcd\xc0\xfa\x0bw\x19/\xe3\xc5\xf7\xcf\xce\x9f\x1f\xf0\x19\x1e\xd5\x8f\xe9\xfc\xdb\xf3\x1f\xdd\xdb\xc7\xf3_Q\xc1y\xfe\xff4\xf3\xff\xecI\x9f=\xe9\xbf\xf7\xa4\xcf\xa8\xf8\x9f\xf3!\xe8\xfe\xeca&\xbfy\xbb\xbe\xb9\xfe\x11\xd6\x02\xcb\xffs\xe1\xf1\xfeO\x0e\xf5\xbc\xff\xf3\x13\xe1\xff\x97\xcb\xbb\xe5n`\xdaW\xab\x81U\xe12\x9f!\xe0\xfc9\x7f\xce\x9f\xf3\xe7\xfc9\x7f\xce\x9f\xf3\xe7\xfc9\x7f\xce\x9f\xf3\xe7\xfc9\x7f\xfe\x9d>\x7f\x03{\xaas\x80\x00P\x05\x00'
```

If you could do that, that would be great, I'd really like to diagnose this issue, thanks!

**Comment by SucyLi** [comment]
Hi, thanks for your help! I was able to do step 1 and 2, but an error occurred when I ran 

`source activate neuro && python -c "from pyns import Neuroscout; print(Neuroscout().analyses.bundle('wJ3ex'))"`

```
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f04804c3080>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='neuroscout.org', port=443): Max retries exceeded with url: /api/analyses/wJ3ex/bundle (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f04804c3080>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/pyns/models/analysis.py", line 141, in bundle
    bundle = self.get(id=id, sub_route='bundle')
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/pyns/api.py", line 106, in _make_request
    headers=headers, params=params)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='neuroscout.org', port=443): Max retries exceeded with url: /api/analyses/wJ3ex/bundle (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f04804c3080>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

Any ideas why the docker environment can't connect?

**Comment by adelavega** [comment]
Will you try one more thing?

After this:
```
docker run --rm -it --entrypoint=bash  neuroscout/neuroscout-cli
```

Try pinging a known stable server like Google:
```
ping www.google.com
```

and ping our server
```
ping neuroscout.org
```

What do you see? It's possible that your server has some sort of firewall.

**Comment by SucyLi** [comment]
Here's what I see:
```
root@c685a6ad2fa9:/work# ping www.google.com
ping: Lacking privilege for raw socket.
root@c685a6ad2fa9:/work# ping neuroscout.org
ping: Lacking privilege for raw socket.
```

**Comment by adelavega** [comment]
Okay, this looks like your Docker environment is having general connectivity issues. 

Not really sure what the solution is, but you can try to restart the docker service or re-install docker. 

You may want to make sure these steps were run as well:

https://docs.docker.com/engine/install/linux-postinstall/

**Comment by adelavega** [comment]
I'm going to close this as this seems like an environment specific bug but let me know if you need any more help troubleshooting.
