### ISSUE TITLE
Drop runs from BIDS Stats Model if no runs are excluded 

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#968]
A limitation of the BIDS Stats Model is that when subjects have different run labels, it is impossible to say which runs to include for which subjects.

For example, in the the `narratives` dataset, task: `pieman`, some subjects have two runs (number: 1, 2), whereas some subjects only have one run (number: 1) and other subjects only have a run but with no run number.

Neuroscout sets the `runs` object in the `Inputs` section of the StatsModel to `[1, 2]` because it takes the set of all run numbers selected.

However, this will cause loading for subjects with no run numbers to fail, because in `analysis.setup()` the default selectors will come from the model, even for subjects with no run numbers.

I suggest as a quick fix that if we detect that all runs are selected, then `runs` is not included in the `Inputs` section.
(Note we need to do this otherwise fitlins will also choke on execution)

An alternative would be th drop `runs` from `Input` all together, as there are other weird edge case scenarios where there could be clashes. For example, if for subjects 1-10 you use run 1, but then 10-20 you use run 2. 

Since in Neuroscout we only ever include events for the specific runs we select, I think it should be OK to do this.

Thoughts? 

cc: @effigies @rwblair

**Comment by effigies** [comment]
Yeah, that sounds fine. What's the reasoning for allowing users to exclude runs in the first place?

**Comment by adelavega** [comment]
No specific use case, just general flexibility. Ideally, the `StatsModel` should allow this as well.

I can imagine a scenario where I only want to look at the first run of a task because I know the content is different from the second run (but this was not encoded).

Or perhaps you just want to try something out and have it run faster. Or perhaps you know run 2 for subject 10 is faulty.

Either way, the current `StatsModel` is not very good at specifying this and its probably an edge case to need this.

**Comment by adelavega** [comment]
This fixes my issue on Neuroscout. Currently running a model to see if it'll run on fitlins.

If so, @rwblair can you implement this change? Just drop `runs` altogether from `Input`.

**Comment by rwblair** [comment]
Ok I went ahead and removed it and committed to my current open PR, deployed to deepdream. Commit in case I need to cherry pick into its own PR:
e47fe297734b57002f2115d4533a49cde7dedb4d

**Comment by adelavega** [comment]
Argh, so I actually just tested it on fitlins/pybids and looks like pybids crashes when there is no `Run` specified. 

Can you cherry pick it please until I get the bottom of this?

**Comment by adelavega** [comment]
On model `myznx` with `Run` popped, fitlins fails. It's likely because the `analysis.setup()` step is taken all at once, whereas in neuroscout we do it by run incrementally:

```
210729-20:35:09,616 nipype.workflow ERROR:
         could not run node: fitlins_wf.loader
ERROR:nipype.workflow:could not run node: fitlins_wf.loader
INFO:numexpr.utils:Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/bin/neuroscout", line 33, in <module>
    sys.exit(load_entry_point('neuroscout-cli', 'console_scripts', 'neuroscout')())
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/neuroscout_cli/cli.py", line 70, in main
    command(deepcopy(args)).run()
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/neuroscout_cli/commands/run.py", line 76, in run
    retcode = run_fitlins(fitlins_args)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/cli/run.py", line 286, in run_fitlins
    analysis.setup(**selectors)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/analysis/analysis.py", line 104, in setup
    self.finalize(**selectors)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/analysis/analysis.py", line 112, in finalize
    step.setup(input_contrasts, **kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/analysis/analysis.py", line 262, in setup
    input_grps = self._merge_contrast_inputs(inputs) if inputs else {}
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/analysis/analysis.py", line 233, in _merge_contrast_inputs
    data = data.groupby(ent_cols).sum()
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/pandas/core/generic.py", line 7894, in groupby
    **kwargs
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 2522, in groupby
    return klass(obj, by, **kwds)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 391, in __init__
    mutated=self.mutated,
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/pandas/core/groupby/grouper.py", line 621, in _get_grouper
    raise KeyError(gpr)
KeyError: 'run
```

**Comment by adelavega** [comment]
This seems like a pybids bug honestly, but I'll probably put off fixing it until we release the new `modeling` module.

In the meantime trying to see if setting `Run` to `null` will do the trick.

**Comment by adelavega** [comment]
Update with `run` set to `null`, fitlins is able to execute, but crashes on the model report stage. 

This should be moved over to fitlins/pybids, as its a bug in the latter, really.

```
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/bin/neuroscout", line 33, in <module>
    sys.exit(load_entry_point('neuroscout-cli', 'console_scripts', 'neuroscout')())
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/neuroscout_cli/cli.py", line 70, in main
    command(deepcopy(args)).run()
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/neuroscout_cli/commands/run.py", line 76, in run
    retcode = run_fitlins(fitlins_args)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/cli/run.py", line 288, in run_fitlins
    write_full_report(report_dict, run_context, deriv_dir)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/viz/reports.py", line 131, in write_full_report
    {'model': model}, PATH_PATTERNS, validate=False))
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/layout/layout.py", line 1193, in build_path
    "Unable to construct build path with source {}".format(source))
ValueError: Unable to construct build path with source {'model': ''}
```
